# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... ***REMOVED***:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "vmd" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2f48bd50-c19b-48df-b468-6a2aa20c6950";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" "noatime" ];
    ***REMOVED***;

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/2f48bd50-c19b-48df-b468-6a2aa20c6950";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" "noatime" ];
    ***REMOVED***;

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/2f48bd50-c19b-48df-b468-6a2aa20c6950";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    ***REMOVED***;

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/2f48bd50-c19b-48df-b468-6a2aa20c6950";
      fsType = "btrfs";
      options = [ "subvol=persist" "compress=zstd" "noatime" ];
    ***REMOVED***;

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/2f48bd50-c19b-48df-b468-6a2aa20c6950";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd" "noatime" ];
      neededForBoot = true;
    ***REMOVED***;

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
***REMOVED***
